create table tbl1 (name Varchar(15), value Integer);
insert into tbl1 values ('Adams',1);
insert into tbl1 values ('Boston',2);
insert into tbl1 values ('Chicago',3);
insert into tbl1 values ('Denver',4);
insert into tbl1 values ('Easy',5);
insert into tbl1 values ('Frank',6);
insert into tbl1 values ('George',7);
insert into tbl1 values ('Henry',8);
insert into tbl1 values ('Ida',9);
insert into tbl1 values ('John',10);
insert into tbl1 values ('King',11);
insert into tbl1 values ('Lincoln',12);
insert into tbl1 values ('Mary',13);
insert into tbl1 values ('New York',14);
insert into tbl1 values ('Ocean',15);
insert into tbl1 values ('Peter',16);
insert into tbl1 values ('Queen',17);
insert into tbl1 values ('Roger',18);
insert into tbl1 values ('Sugar',19);
insert into tbl1 values ('Thomas',20);
insert into tbl1 values ('Union',21);
insert into tbl1 values ('Victor',22);
insert into tbl1 values ('William',23);
insert into tbl1 values ('X-ray',24);
insert into tbl1 values ('Young',25);
insert into tbl1 values ('Zero',26);
create table salary (name Varchar(15), value real);
insert into salary values ('John Smith',1000000);
insert into salary values ('Jane Smith',2000000);
insert into salary values ('Mark Smith',3000000);
insert into salary values ('Nancy Smith',4000000);
.quit
